import { Platform, StyleSheet } from 'react-native';

export const getStyles = (isDarkMode: boolean, colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    contentContainer: {
      paddingHorizontal: 20,
      paddingBottom: 32,
    },
    header: {
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'ios' ? 60 : 40,
      paddingBottom: 20,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    backButton: {
      width: 45,
      height: 45,
      borderRadius: 22.5,
      backgroundColor: colors.cardBackground,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      marginRight: 15,
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: colors.text,
    },
    subtitle: {
      fontSize: 16,
      color: colors.secondary,
      marginTop: 5,
    },
    feedbackContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 30,
      gap: 16,
    },
    feedbackText: {
      fontSize: 15,
      color: colors.secondary,
      textAlign: 'center',
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 24,
    },
    summaryCard: {
      width: '48%',
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 18,
      borderWidth: 1,
      borderColor: colors.border,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
    },
    summaryValue: {
      fontSize: 24,
      fontWeight: 'bold',
      color: colors.primary,
      marginBottom: 6,
    },
    summaryLabel: {
      fontSize: 13,
      color: colors.secondary,
      lineHeight: 18,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
    },
    refreshText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
    },
    emptyStateContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 40,
      paddingVertical: 32,
    },
    emptyStateIconBox: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: colors.cardBackground,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 25,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    emptyStateTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 10,
    },
    emptyStateDescription: {
      fontSize: 15,
      color: colors.secondary,
      textAlign: 'center',
      lineHeight: 22,
    },
    retryButton: {
      marginTop: 8,
      backgroundColor: colors.primary,
      paddingHorizontal: 18,
      paddingVertical: 12,
      borderRadius: 14,
    },
    retryButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: 'bold',
    },
    alertCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.cardBackground,
      borderRadius: 22,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    alertIconBox: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: isDarkMode ? '#2A2122' : '#FFF0F2',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    alertBody: {
      flex: 1,
    },
    alertTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      marginBottom: 8,
    },
    alertTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.text,
    },
    sourceBadge: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    sosBadge: {
      backgroundColor: isDarkMode ? '#4A1F25' : '#FDE5EA',
    },
    ocorrenciaBadge: {
      backgroundColor: isDarkMode ? '#2B2A20' : '#FFF2D9',
    },
    sourceBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.text,
    },
    alertDescription: {
      fontSize: 14,
      color: colors.secondary,
      lineHeight: 20,
      marginBottom: 10,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
      gap: 6,
    },
    metaText: {
      flex: 1,
      fontSize: 13,
      color: colors.secondary,
    },
    dateText: {
      marginTop: 6,
      fontSize: 12,
      color: colors.secondary,
    },
  });
