import { StyleSheet, Platform } from 'react-native';

export const getStyles = (isDarkMode: boolean, colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDarkMode ? colors.cardBackground : '#FFF',
  },
  header: {
    backgroundColor: isDarkMode ? colors.cardBackground : '#FFF',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 15 : 10,
    paddingBottom: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  headerContent: {
    flexDirection: 'column',
    flex: 1,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerBellButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerBellBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
    borderWidth: 2,
    borderColor: isDarkMode ? colors.cardBackground : '#FFF',
  },
  headerBellBadgeText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  headerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    overflow: 'hidden',
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  headerAvatarText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: 'bold',
  },
  headerGreeting: {
    fontSize: 14,
    color: colors.secondary,
    marginBottom: 2,
  },
  headerName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
  },
  scrollView: {
    flex: 1,
    backgroundColor: isDarkMode ? colors.background : '#FFECF4',
  },
  content: {
    padding: 20,
    paddingBottom: 100,
  },

  // Card de status "Você está Protegida"
  statusCard: {
    borderRadius: 30,
    padding: 22,
    marginBottom: 26,
    elevation: 5,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  statusCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  statusCardLabel: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '600',
  },
  statusCardTitle: {
    fontSize: 24,
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginTop: 2,
  },
  statusCardIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.22)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusBadgesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
    gap: 5,
  },
  statusBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },

  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  sectionLink: {
    color: colors.primary,
    fontWeight: 'bold',
    fontSize: 13,
  },

  // Ações rápidas
  quickAccessGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 26,
  },
  quickAccessCard: {
    width: '48%',
    backgroundColor: colors.cardBackground,
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  quickAccessIconBox: {
    width: 42,
    height: 42,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  quickAccessLabel: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '700',
    marginBottom: 2,
  },
  quickAccessSubLabel: {
    fontSize: 11,
    color: colors.secondary,
  },

  // Círculo de confiança
  trustCircleRow: {
    flexDirection: 'row',
    marginBottom: 28,
  },
  trustCircleItem: {
    alignItems: 'center',
    marginRight: 18,
    width: 60,
  },
  trustCircleAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  trustCircleAvatarText: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  trustCircleName: {
    fontSize: 11,
    color: colors.text,
    textAlign: 'center',
  },
  trustCircleAddButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: 'dashed',
    backgroundColor: colors.cardBackground,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },

  occurrenceCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: 25,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  occurrenceIconBox: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  occurrenceTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
  },
  occurrenceDescription: {
    fontSize: 13,
    color: colors.secondary,
    lineHeight: 18,
  },
  occurrenceTime: {
    fontSize: 11,
    color: colors.secondary,
    flexShrink: 1,
  },
  occurrenceInfo: { flex: 1, gap: 6 },
  occurrenceTimeRow: { flexDirection: 'row', alignItems: 'center', gap: 4, flexShrink: 1 },
  occurrenceCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    rowGap: 6,
    columnGap: 10,
  },
  occurrenceActionsRow: {
    flexDirection: 'row',
    gap: 10,
    flexShrink: 0,
  },
  occurrenceActionButton: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDarkMode ? colors.accent : '#F5F5F7',
  },
  occurrenceActionButtonDanger: {
    backgroundColor: isDarkMode ? 'rgba(229,57,53,0.16)' : '#FDECEC',
  },

  // Estado vazio de "Ocorrências Recentes"
  emptyOccurrenceCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: 26,
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  emptyOccurrenceIconBox: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: isDarkMode ? colors.accent : '#E8F8EE',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyOccurrenceTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
  },
  emptyOccurrenceSubtitle: {
    fontSize: 13,
    color: colors.secondary,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 19,
    paddingHorizontal: 8,
  },
  // Botão de destaque para registrar ocorrência, logo abaixo do cabeçalho da seção
  recentRegisterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: 14,
    marginBottom: 15,
    elevation: 4,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  recentRegisterButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },

  recentSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },

  // Barra de navegação inferior com SOS elevado
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: colors.cardBackground,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 30 : 15,
    elevation: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconActive: {
    backgroundColor: isDarkMode ? colors.accent : '#FDF2F4',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 18,
    alignItems: 'center',
  },
  navLabel: {
    fontSize: 10,
    color: colors.secondary,
    marginTop: 4,
  },
  navLabelActive: {
    color: colors.primary,
    fontWeight: 'bold',
  },
  sosNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  sosNavButtonTouchable: {
    marginTop: -48,
    borderRadius: 40,
    elevation: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.45,
    shadowRadius: 12,
  },
  sosNavButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 6,
    borderColor: isDarkMode ? colors.cardBackground : '#FFFFFF',
  },
  sosNavButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.cardBackground,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  closeButton: {
    padding: 5,
  },
  moreActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  moreActionsIconBox: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  moreActionsLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },

  // Modal de edição de ocorrência (aberto a partir dos cards da home)
  editTypeRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  editTypeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: isDarkMode ? colors.border : '#EDEDED',
    backgroundColor: isDarkMode ? colors.accent : '#FFFFFF',
  },
  editTypeChipActiveError: {
    backgroundColor: '#E53935',
    borderColor: '#E53935',
  },
  editTypeChipActiveWarning: {
    backgroundColor: '#FB8C00',
    borderColor: '#FB8C00',
  },
  editTypeChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  editTypeChipTextActive: {
    color: '#FFFFFF',
  },
  editInput: {
    backgroundColor: isDarkMode ? colors.accent : '#FAFAFA',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.text,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: isDarkMode ? colors.border : '#EDEDED',
  },
  editTextArea: {
    height: 90,
    textAlignVertical: 'top',
  },
  editSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 15,
  },
  editSaveButtonDisabled: {
    opacity: 0.5,
  },
  editSaveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },

  // Estilos do popup de ativação de localização
  locationPopupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  locationPopupContent: {
    backgroundColor: colors.cardBackground,
    borderRadius: 30,
    padding: 30,
    alignItems: 'center',
    width: '100%',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  locationPopupIconBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  locationPopupTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 12,
    textAlign: 'center',
  },
  locationPopupDescription: {
    fontSize: 15,
    color: colors.secondary,
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 22,
  },
  locationPopupButton: {
    width: '100%',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  locationPopupButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  locationPopupCancelButton: {
    width: '100%',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationPopupCancelText: {
    color: colors.secondary,
    fontSize: 15,
    fontWeight: '600',
  },
});
