import { StyleSheet, Platform } from 'react-native';

export const getStyles = (isDarkMode: boolean, colors: any) => StyleSheet.create({
  // Botão SOS grande com brilho (usado na confirmação e no estado ativo)
  sosGlowWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosGlowOuter: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: isDarkMode ? '#2D1619' : '#FCE4E8',
  },
  sosGlowInner: {
    position: 'absolute',
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: isDarkMode ? '#3D1A20' : '#F9D0D7',
  },
  sosGradientButton: {
    width: 160,
    height: 160,
    borderRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 10,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
  },

  // --- Tela inicial (pedido de ajuda) ---
  promptContainer: {
    flex: 1,
    backgroundColor: isDarkMode ? colors.background : '#FFECF4',
  },
  promptHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 15 : 10,
    paddingBottom: 10,
  },
  promptHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  promptHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  promptBellButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,255,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  promptBellBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
    borderWidth: 2,
    borderColor: isDarkMode ? colors.background : '#FFECF4',
  },
  promptBellBadgeText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  promptAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    overflow: 'hidden',
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  promptAvatarText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: 'bold',
  },
  promptTitleWrap: {
    paddingHorizontal: 24,
    marginTop: 10,
    marginBottom: 30,
  },
  promptTitle: {
    fontSize: 25,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 10,
  },
  promptSubtitle: {
    fontSize: 14,
    color: colors.secondary,
    lineHeight: 21,
  },
  holdWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
  },
  holdRing: {
    position: 'absolute',
  },
  holdButtonText: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: 'bold',
  },
  holdButtonSubtext: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    marginTop: 3,
  },
  promptQuickRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  promptQuickButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardBackground,
    borderRadius: 18,
    paddingVertical: 16,
    gap: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  promptQuickButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  promptEmergencyLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 20,
  },
  promptEmergencyLinkText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  promptLocationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    borderRadius: 20,
    padding: 16,
    marginHorizontal: 24,
    marginBottom: 20,
    gap: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  promptLocationIconBox: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  promptLocationLabel: {
    fontSize: 12,
    color: colors.secondary,
    marginBottom: 2,
  },
  promptLocationValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.text,
  },

  // --- Estados "sending" e "active" ---
  flowContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  flowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 15 : 10,
    paddingBottom: 10,
  },
  flowBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  flowHeaderTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
  },
  flowContent: {
    flexGrow: 1,
    alignItems: 'center',
    padding: 24,
  },
  flowTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 10,
  },
  flowSubtitle: {
    fontSize: 14,
    color: colors.secondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 32,
    paddingHorizontal: 12,
  },
  progressRingWrapper: {
    marginBottom: 36,
  },
  progressCountdown: {
    fontSize: 34,
    fontWeight: 'bold',
    color: colors.primary,
  },
  progressLabel: {
    fontSize: 12,
    color: colors.secondary,
    fontWeight: '600',
    letterSpacing: 1,
    marginTop: 2,
  },
  cancelAlertLink: {
    marginTop: 24,
    marginBottom: 12,
  },
  cancelAlertLinkText: {
    color: colors.secondary,
    fontSize: 15,
    fontWeight: '600',
  },

  // Lista de contatos notificados
  contactsList: {
    width: '100%',
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    borderRadius: 18,
    padding: 12,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  contactAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  contactAvatarText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.text,
  },
  contactStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    gap: 5,
  },
  contactStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4CAF50',
  },
  contactStatusText: {
    fontSize: 12,
    color: colors.secondary,
  },
  contactCallButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Estado ativo: botão SOS grande
  activeSosWrapper: {
    marginBottom: 20,
  },
  activeSosButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 6,
  },
  activeSosButtonSubtext: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  activeStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 28,
  },
  activeStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4CAF50',
  },
  activeStatusText: {
    fontSize: 13,
    color: colors.secondary,
    fontWeight: '600',
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 28,
    gap: 12,
  },
  quickActionButton: {
    flex: 1,
    backgroundColor: colors.cardBackground,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  quickActionIconBox: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: isDarkMode ? colors.accent : '#FFF0F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickActionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.text,
    textAlign: 'center',
  },
});
